server:
  port: 8080
  servlet:
    context-path: /spring-aws-s3

application:
  version: 1.0.0
  service-name: spring_aws_s3

spring:
  datasource:
    hikari:
      connection-test-query: SELECT 1 # FROM DUAL
      minimum-idle: 1
      maximum-pool-size: 5
    url: jdbc:postgresql://localhost:5432/aws_database
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#      properties:
#        hibernate:
#          dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

aws-config:
  s3:
    endpointUrl: https://s3.ap-southeast-1.amazonaws.com
    accessKey: accessKey_value
    secretKey: secretKey_value
    bucketName: txtlab-bucket
    bucket-select: txtlab-bucket
    csv-object-key: aws_s3_students.csv
    select-results-path: D:/test

